### PR TITLE
Updated UI to show multiple connected devices.

### PR DESCRIPTION
**Pull request by g-ortuno**
The app will now show the number of connected devices rather than
the address of the last connected device.

device-2015-04-15-154020

[Review on Reviewable](https://reviewable.io/reviews/webbluetoothcg/ble-test-peripheral-android/33)

### CODE REVIEW

**Comment by scheib** [comment]
Reviewed files:
- app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java @ r1
- app/src/main/res/values/strings.xml @ r1

---

<sup>**[app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java, line 180 \[r1\]](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33#-JmzVK3oVB1CAGw1G-lK)** ([raw file](https://github.com/webbluetoothcg/ble-test-peripheral-android/blob/29e400b167ad681b7f56e3d0555523a8cc7e13f2/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java#L180)):</sup>
This line looks like noise, did you intend it?

---

<sup>**[app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java, line 285 \[r1\]](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33#-JmzWFd5xE7A2FBREaIj)** ([raw file](https://github.com/webbluetoothcg/ble-test-peripheral-android/blob/f45926774026d6ae17c388a2000c4c1ea8409ad3/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java#L285)):</sup>
From (newState == BluetoothGatt.STATE_DISCONNECTED) this code can be called and end up reporting 0 devices connected, but not go back to using status_notConnected. My vote, just remove status_notConnected entirely.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33)

**Comment by g-ortuno** [comment]
<sup>**[app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java, line 180 \[r1\]](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33#-JmzVK3oVB1CAGw1G-lK)** ([raw file](https://github.com/webbluetoothcg/ble-test-peripheral-android/blob/29e400b167ad681b7f56e3d0555523a8cc7e13f2/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java#L180)):</sup>
Done.

---

<sup>**[app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java, line 285 \[r1\]](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33#-JmzWFd5xE7A2FBREaIj)** ([raw file](https://github.com/webbluetoothcg/ble-test-peripheral-android/blob/f45926774026d6ae17c388a2000c4c1ea8409ad3/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java#L285)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33)

**Comment by scheib** [comment]
Reviewed files:
- app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java @ r2
- app/src/main/res/values/strings.xml @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webbluetoothcg/ble-test-peripheral-android/33)

**Comment by scheib** [comment]
The previous comment is Reviewable.io's LGTM I suppose. It's more obvious when viewing the pull request in Reviewable.

**Pull request merged**
