### PR TITLE
Keep the Screen On when advertising

### PR DESCRIPTION
**Pull request by beaufortfrancois**
I find myself using this app often these days and keeping the screening on when advertising would really help me.

image

### CODE REVIEW

**Comment by scheib** [comment]
App should include explanation on screen that the broadcast will continue only while the screen is on, and that is why the screen is kept on.

**Comment by beaufortfrancois** [comment]
Will add these explanation then. Thanks for the feedback!

**Comment by beaufortfrancois** [comment]
I simply appended "(Keep Screen On)". WDYT?
toto

**Comment by g-ortuno** [comment]
Good idea! Thanks!

**Pull request merged**
